<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOyRMrcO\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOyRMrcO/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOyRMrcO.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOyRMrcO\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerOyRMrcO\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'OyRMrcO',
    'container.build_id' => '7b21f93d',
    'container.build_time' => 1520411489,
));
